### PR TITLE
filter tables lazy loaded using dbplyr

### PR DESCRIPTION
**Pull request by SimonCoulombe**
this refers to this issue:

https://github.com/dgkf/shinyDataFilter/issues/26

This is a fantastic module, but my main shiny usage is with databases, so it wasnt compatible.
I created a pull request with code that "works".
However:

I had to give up on the "filtering at every step" as you add filters. instead the filtering only occurs at the end when displaying the resulting table.
character column are treated as factors (because there are no factors in databases)
The full vector is being downloaded from the database when creating the filters. It would be much better to download the counts of each possible values. (better to get the count of male and female instead of getting a 6-million long character vector).

### CODE REVIEW

**Comment by dgkf** [comment]
This is really cool! I completely agree that making this tool more data-representation-agnostic would be super helpful for being able to accommodate database handles. 

It looks like a lot of the changes are rather specific to your use case, so I just want to make sure I'm understanding the purpose of the PR before I do a code review. Are you hoping to contribute these changes, or is the purpose of this PR primarily for sharing the tweaks you had to make to accommodate this behavior?

**Comment by SimonCoulombe** [comment]
Hi Doug,

Thanks for reaching out!   

All the changes aim to make the module compatible with tables lazy loaded with "dbplyr"  while remaining compatible with the in-memory dataframes you were already using. Most of the changes are very cosmetic, like replacing `names()` with `colnames()` and  `nrow()` with `dplyr::tally()`.   I also "collect()" the data that is passed to vec

I dont think this code is ready to be merged in your repo without some improvements as it breaks a couple things.  I can live with these things for my use.   The purpose of this PR is mostly sharing in case someone else finds it useful as it is. However, if someone knowledgeable enough found it useful/interesting enough to fix it and merge into your package I would be extactic.  I just don't know enough about  Map/Reduce/Filte/bquote/exprs/do.call/parse to get there.   

### Breaking changes I can think of:

#1
[R/shiny_data_filter_item.R] : 
`out_data <- if (!nrow(data())) data() `
becomes
`out_data <- if (FALSE) {data()} #(!nrow(data())) data()`
because I wasnt sure how to deal with that nrow()  


#2 
[R/shiny_vector_filter_XXXX.R]
In all these files I replaced 
 module_return$mask <- shiny::reactive({eval(do.call(substitute, list(module_return$code(), list(.x = x()))))})
with
  module_return$mask <- shiny::reactive({    TRUE  })
because `shiny_data_filter_item` returned a syntax error when trying to do the "subset" thing.  
maybe we could just eval(parse(module_return$code)) inside that subset?   

#3  

`shiny_vector_filter.character.R`  just points to shiny_vector_filter.factor.R  because factors are converted to characters in the DB)


### Improvements I can think of:  

Downloading the full vector and passing it to `shiny_vector_filter()` is quite expensive on a table with millions of rows with mostly identical values.  It would be more efficient to download the "counts" of each values and pass that table to a new  `shiny_table_filter()` that workds on `tables` instead of vector.

**Comment by dgkf** [comment]
Awesome - thanks for sharing your progress on this.

There are a few design choices I'd want to iron out before I'd feel comfortable introducing this behavior.

- I'd like to leverage some generic methods that can dispatch on either a base R `data.frame` or a database connection to apply the filters. `shiny_vector_filter` could be replaced with something like `shiny_column_filter(<data>, <colname>, ...)` such that there is a separate implementation for 
   - `shiny_column_filter.data.frame`, which can leverage the current `shiny_vector_filter`
   - `shiny_column_filter.db_connection`, which can have special handling for pulling informative diagnostic info from a database without having to fetch all the data
   - This could also be more easily extended to work for other exotic data structures like an `igraph`, sparse matrix, etc.
- After migrating to generics, I'd prefer to avoid the `dplyr`/`dbplyr` dependencies - these can still live in the database specific handlers, but as Suggested packages scoped to just those functions that require them. My hope would be to just use the `DBI` connection object as a rather low-level interface, thought he emitted code could definitely serve the `dbplyr` use case.
- I'd need to investigate how you've handled the masking a bit more closely. My understanding of `dbplyr` is that it lazily constructs a sql query, so the mask-style filtering wouldn't work here. I think you've addressed that, but I need to check my `dbplyr` understanding before I can effectively review your work.

Let me know if you would be interested in polishing the PR to accommodate that sort of a design.

**Comment by SimonCoulombe** [comment]
Hi Doug! 
Having  generic methods and keeping dplyr/dbplyr as "suggest" dependencies sound  like good ideas.  

I have already spent an unreasonable amount of time just getting the module to work with  dbplyr in this rough shape.  I dont think I can tell my manager I still need to work on the filters in  that stupid shiny app he requested :)  I really can't promise anything, but if I have a night of insomnia in the next few weeks I'll try to improve it.

**Comment by dgkf** [comment]
No worries at all. I appreciate you sharing your work and I hope it can live on - either through being refined or as inspiration.

I'm going to close this PR for now if there isn't an immediate intention to polish it for contribution, but I'm glad that it's here for posterity. 

Thanks for sharing your experience using the tool and your work in adapting it to your needs.

**Pull request closed without merging**
